"""empty message

Revision ID: 1da2a4aed46f
Revises: e156032bc0ef
Create Date: 2018-02-23 23:45:11.002255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1da2a4aed46f'
down_revision = 'e156032bc0ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_withdrawn', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_withdrawn')
    # ### end Alembic commands ###
